site_name: My Docs
theme:
    name: material
    palette:
      scheme: "slate" # Pour un thème sombre

nav:  
  - Contexte: contexte.md
  - Infrastructure:
      - Schéma Réseau: Schéma-réseau.md
      - VLAN: VLAN.md
      - Équipements: Equipements.md
  - Configuration:
      - Cœur de Réseau: Coeur-de-réseau.md
      - Routeurs: Routeurs.md
      - Protocoles:
          - HSRP: HSRP.md
          - Firewall: Firewall.md
          - RDP: RDP.md
  - Machines Virtuelles:
      - Windows Serveur: Windows-Serveur.md
      - Debian: Debian.md
