site_name: Infrastructure Orleans 2024/2025
copyright: Copyright &copy; 2023 - 2025 Elouenn ROUSSEAU; Kevin SOULIER; Erwan BRIET
theme:
    name: material
    logo: "images/s.png"
    palette:
      scheme: slate
      primary: amber
      accent: amber
      theme:

    
extra_css:
  - extra.css 

nav:  
  - Accueil: index.md
  - Infrastructure:
      - Réseau: Réseau.md
      - VLAN: VLAN.md
  - Équipements:
     - Cœur de Réseau:
        - Configuration: Conf-Coeur-de-réseau.md
     - Routeurs:
        - Configuration: Conf-Routeurs.md
        - HSRP: HSRP.md
        - RDP: Remote-Desktop-Protocol.md
     - Firewall:
        - Configuration: Conf-Firewall.md
        - Certificat SSL : Certificat-ssl.md
  - Machines Virtuelles:
      - Windows Serveur: 
        - Configuration: Conf-Windows-Serveur.md
        - DHCP: Serveur-DHCP.md
        - DNS Redirrecteur: DNS.md
      - Debian:
        - Configuration: Conf-Debian.md
        - Serveur Web: 
          - Apache: Serveur-Apache.md
          - SSL: SSL.md
          - NGINX: 
            - Installation: NGINXinstall.md
            - Reverse proxy: Reverseproxy.md
            - Load balancing: Loadbalencing.md
        - DNS: DNSDEB.md
        - Serveur mail: 
          - Postfix: Postfix.md
          - Dovecot: Dovecot.md
          - Client thunderbird: thunderbird.md
          - LDAP: 
            - Installation LDAP: InstallLDAP.md
            - Modification Postfix: Modifpostfix.md
            - Modification Dovecot: Modifdovecot.md
            - Configuration LDAP: modifLDAP.md
