site_name: Infrastructure Orleans 2024/2025
theme:
    name: material
    logo: "images/logo.png"
    palette:
      scheme: "slate" # Pour un thème sombre
extra_css:
  - extra.css 

nav:  
  - Accueil: index.md
  - Infrastructure:
      - Réseau: Réseau.md
      - VLAN: VLAN.md
  - Équipements:
     - Cœur de Réseau:
        - Configuration: Conf-Coeur-de-réseau.md
     - Routeurs:
        - Configuration: Conf-Routeurs.md
        - HSRP: HSRP.md
        - RDP: Remote-Desktop-Protocol.md
     - Firewall:
        - Configuration: Conf-Firewall.md
        - Certificat SSL : Certificat-ssl.md
  - Machines Virtuelles:
      - Windows Serveur: 
        - Configuration: Conf-Windows-Serveur.md
        - DHCP: Serveur-DHCP.md
        - DNS Redirrecteur: DNS.md
      - Debian:
        - Configuration: Conf-Debian.md
        - Serveur Apache: Serveur-Apache.md
